"""Generate the VERSIONINFO resource PyInstaller stamps into an executable.

An executable with no company, product or version fields looks anonymous both
to a person reading its properties and to the heuristics that decide whether an
unsigned binary is worth warning about. The values come from the package itself
so they cannot drift from the release.

Usage:
    python packaging/make_version_file.py <name> <description> <output>
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

from tacz_validator import __version__  # noqa: E402

COMPANY = "N4sT7eR"
PRODUCT = "TaCZ Gunpack Validator"
COPYRIGHT = "Copyright (c) 2026 N4sT7eR. MIT License."

TEMPLATE = """# Generated by packaging/make_version_file.py -- do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numeric},
    prodvers={numeric},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', {company!r}),
          StringStruct('FileDescription', {description!r}),
          StringStruct('FileVersion', {version!r}),
          StringStruct('InternalName', {name!r}),
          StringStruct('LegalCopyright', {copyright!r}),
          StringStruct('OriginalFilename', {filename!r}),
          StringStruct('ProductName', {product!r}),
          StringStruct('ProductVersion', {version!r}),
        ],
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def numeric_version(version: str):
    """Windows wants exactly four integers, e.g. 0.9.1 -> (0, 9, 1, 0)."""
    parts = []
    for piece in version.split(".")[:4]:
        digits = "".join(ch for ch in piece if ch.isdigit())
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts)


def main(argv) -> int:
    if len(argv) != 4:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    name, description, output = argv[1], argv[2], argv[3]
    with open(output, "w", encoding="utf-8") as handle:
        handle.write(
            TEMPLATE.format(
                numeric=numeric_version(__version__),
                company=COMPANY,
                description=description,
                version=__version__,
                name=name,
                copyright=COPYRIGHT,
                filename=name + ".exe",
                product=PRODUCT,
            )
        )
    print("{} -> {} ({})".format(name, output, __version__))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
